### ISSUE TITLE
Update Job Listing Template to match/include info from Legacy.

### ISSUE THREAD

**Issue by claudiosanchez** [Emplea-do/emplea_do#107]
The current Job Listing Template (```JobResultItemView.cshtml```) does not match the data available for the Job.

As the diagram below shows, the following items need to be addressed: 
![image](https://user-images.githubusercontent.com/2293759/68413831-6bcad100-0165-11ea-8ed9-dc61fad3d2e1.png)

<img width="1051" alt="Screen Shot 2019-11-07 at 1 46 47 PM" src="https://user-images.githubusercontent.com/2293759/68413692-1bec0a00-0165-11ea-82cf-c0f31800dcb8.png">

**Comment by 3pa2** [comment]
mio

**Comment by robertlluberes** [comment]
Just updating the actual status of this Issue ℹ:

**Is missing the email or company email to apply** ⚠, view image comparison below:

![image](https://user-images.githubusercontent.com/13991439/84549684-991cc600-acd6-11ea-9ca6-1a59e002d94d.png)

---
---
Another thing, is better to use the icon `ti-thumb-up` for like, looks better 👍🏼:
![image](https://user-images.githubusercontent.com/13991439/84549269-979ece00-acd5-11ea-97dc-e73dee2114b4.png)

**Comment by claudiosanchez** [comment]
## Update on the issue
- The Email of the Job poster is no longer required. We are moving away from Applying via email only.
- The suggestion to use ti-thumb-up sounds great! 

Anyone can pick up this issue and create a PR.

**Comment by claudiosanchez** [comment]
@3pa2 @robertlluberes ^

**Comment by robertlluberes** [comment]
I will take it, since the email is no longer required I just have to change the like icon.
