### ISSUE TITLE
Agregar Microsoft como una opción de Login

### ISSUE THREAD

**Issue by ljcordero** [Emplea-do/emplea_do#114]
**Actual:**
No esta disponible la opción de autenticarse con Microsoft.

![image](https://user-images.githubusercontent.com/29816580/71563499-2644c900-2a6f-11ea-86fd-324bb5384630.png)

**Esperado:**
Como en el site anterior poder autenticarse con Microsoft.

![image](https://user-images.githubusercontent.com/29816580/71563493-0ca38180-2a6f-11ea-9ca6-27f6324612b3.png)

**Solo es necesario agregar el Flag de microsoft en el appsettings.**

**Comment by robertlluberes** [comment]
@eatskolnikov me gustaría trabajar este issue

**Comment by eatskolnikov** [comment]
@robertlluberes do it.

Agrega lo siguiente:
[ ] Un feature flag en el appsetings, fíjate en los otros feature flags en el campo de FeatureManager del appsettings.template.json
[ ] El botón de login
[ ] Agrega los pasos para conseguir esos keys a la guía si no están
