### ISSUE TITLE
Minor bugs en job search y fecha de publicación.

### ISSUE THREAD

**Issue by icepeda** [Emplea-do/emplea_do#119]
1- En la pagina de Jobs, el parámetro IsRemote no es nullable, por ende siempre busca IsRemote=False, el comportamiento deseable es que se utilice en  **Sólo mostrar posiciones remotas**.  
2- No se asigna PublishedDate al darle approved al Job.

**Comment by jugomez** [comment]
Voy a estar trabajando esto

**Comment by jugomez** [comment]
Hola @icepeda, he revisado tu issue y tengo los siguientes comentarios

**1- En relación al parametro IsRemote:** Pude comprobar que no existe problema. He realizado las pruebas y todo ha funcionado correctamente. "No se si fue que realizaste tu prueba con los registros mocks ya que ambos son Remote y el filtro siempre los va a incluir"

**2- El caso de la fecha de publicación:** no pude reproducirlo.

**Recomendaciones**

1- Cuando detectas mas de un bug sepáralos en tantos issues como casos detectados
2- El caso de la fecha favor crear un nuevo issue e incluye mas info para poder reproducir la anomalía según se explica en la [siguiente guía ](https://github.com/Emplea-do/emplea_do/blob/development/.github/ISSUE_TEMPLATE/1-bug-report.md)

**Comment by icepeda** [comment]
Hey @jugomez. 

Hubo una confusion con este issue. Paso a explicar; Hice el issue para poder trabajarlo de inmediato y así lo hice. Los cambios ya están en development. La confusion estuvo en que al no tenerla asignada quedo abierta.  De inmediato voy a escribir por slack para que nos ayuden a cerrarla.

Por otro lado, agradezco mucho no solo tus recomendaciones, sino también por reactivar el project.
