### ISSUE TITLE
Podemos Migrar de Core 2.2 to 3.1?

### ISSUE THREAD

**Issue by gromney** [Emplea-do/emplea_do#121]
pregunto porque no se si es necesario ademas no parece tan complicado segun esta 
[guia](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio), imagino que es solo validar que no se rompa nada con los [cambios](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1)
La version utilizada en el proyecto ya no es recomendada. S

![image](https://user-images.githubusercontent.com/781571/80301131-42801a80-8770-11ea-9a88-a4ef2c551d94.png)

**Comment by robertlluberes** [comment]
@gromney tomarás este Issue? Me gustaria trabajar/colaborar en el.

**Comment by eatskolnikov** [comment]
Yo lo tomo @robertlluberes

**Comment by robertlluberes** [comment]
@eatskolnikov Cerraré este Issue, ya que fue trabajando en este PR:

[#170 Refactoring, upgraded to .net core 3.1](https://github.com/Emplea-do/emplea_do/pull/170)
