### ISSUE TITLE
The last stand

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#123]
One big effort to publish the new site

**Fase 1**
- [x] Implementar la nueva pantalla de búsqueda @eddycordero
- [x] Implementar búsqueda desde el home @eddycordero
- [x] Agregar imagen por defecto (no-image) @juniorfelixgb
- [x] Agregar documentación de feature flags @juniorfelixgb
- [x] Agregar .bat para inicialización en windows y documentar en el readme @juniorfelixgb

**Fase 2**
- [x] Análisis del CI
- [x] Adecuación del CI
- [x] Migración y publicación de la aplicación

**Fase 3**
- [x] Confirmar validación por Slack
- [x] Posteo de imágenes por

**Comment by EddyCordero** [comment]
Hey I'm here

**Comment by robertlluberes** [comment]
Count on me

**Comment by eatskolnikov** [comment]
@robertlluberes i'll see what I can assing you

**Comment by eatskolnikov** [comment]
@EddyCordero @juniorfelixgb Pongan un sitrep de lo que tengan hecho y lo que falte en un comentario aquí

**Comment by juniorfelixgb** [comment]
Solo me falta probar la inserción de un Job, aun no he podido validar el
GoogleApiKey
para la validación del no-image.

**Comment by EddyCordero** [comment]
@eatskolnikov  Realice las dos tareas de la primera face.

Vere si le doy la mano a @juniorfelixgb  con lo faltante

**Comment by eatskolnikov** [comment]
Hice algunas ligeras adecuaciones de lo que ya han mandado, ahora voy a ver el tema del CI, la publicación y la migración de los datos.

**Comment by juniorfelixgb** [comment]
Perfecto, cuando tendremos reunión?

**Comment by eatskolnikov** [comment]
@juniorfelixgb 
Como conversamos ustedes van a trabajar esta noche en el feature del mantenimiento de las compañías

**Comment by eatskolnikov** [comment]
Cuando voy a "Mi perfil"
![Screen Shot 2020-06-08 at 10 56 50 PM](https://user-images.githubusercontent.com/1693000/84101262-89059d80-a9db-11ea-90d3-673b30934877.png)

Y doy click en la pestaña de perfiles de empresas
![Screen Shot 2020-06-08 at 10 56 46 PM](https://user-images.githubusercontent.com/1693000/84101259-886d0700-a9db-11ea-9a65-c69b959c6566.png)

Debe verse el listado de mis empresas y luego debo poder editar sus propiedades en la misma ventana.
Las empresas tienen un UserId y en el controller hay un _currentUser.UserId. Usando el CompanyService pueden cargar todas las empresas del usuario y listarlas.

@juniorfelixgb @EddyCordero 
Creen un nuevo ticket (uno solo), trabajen juntos, repartanse la tarea. Es un trabajo en equipo. Comuniquense.

**Comment by eatskolnikov** [comment]
Ya migramos la data, solo falta mover el site de beta a emplea.do
