### ISSUE TITLE
Error al hacer clic en ver todos Home/Index

### ISSUE THREAD

**Issue by jugomez** [Emplea-do/emplea_do#128]
Expected Behavior
Navegar hacia la lista de todos los empleos

Actual Behavior
Cuando se da clic en ver todos en la pagina inicial de la aplicación, Esta mostrando error de NullReferenceException 

Steps to Reproduce the Problem
1- Navegar a la página principal "Home/Index"
2- Hacer clic en el boton Ver Todos

Specifications
Web browser: Ms Edge, G Chrome
Operating system: Win10

![image](https://user-images.githubusercontent.com/3052715/82967106-2e5f5100-9f9a-11ea-8ad5-787885aa158f.png)

**Comment by jugomez** [comment]
Estaré trabajando este caso

**Comment by eatskolnikov** [comment]
@jugomez agrega los links a los issues que estás creando en el issue #123

**Comment by codercampos** [comment]
@eatskolnikov Can We close this issue?
