### ISSUE TITLE
Me gustaría tener un botón para crear nuevos empleos desde mi perfil

### ISSUE THREAD

**Issue by jugomez** [Emplea-do/emplea_do#130]
Como usaurio registrado me gustaría tener un botón que me permita de forma rápida ir a la pagina de crear nuevo empleo

### VISUAL ID's ###
![image](https://user-images.githubusercontent.com/3052715/83054963-2f879100-a021-11ea-8a21-14350b0d37dd.png)

**Comment by eatskolnikov** [comment]
@jugomez ¿donde iría? mejor sería sacar el botón de crear empleo del menú de perfil del usuario.

**Comment by sact1909** [comment]
@eatskolnikov creo que ese boton puede ir aqui

![image](https://user-images.githubusercontent.com/23615129/94976981-cb9c3a00-04e4-11eb-98af-8d6e7d49fa9d.png)
