### ISSUE TITLE
Wrong URL When downloading  Windows and Mac SDK

### ISSUE THREAD

**Issue by ivanatista** [Emplea-do/emplea_do#14]
In the file Readme.md. When You try to download the .NET SDK, the first URL of Windows and Mac are inverted.

The literal of the links are "in this link".
![inverted](https://user-images.githubusercontent.com/9642676/45510860-70fedc80-b769-11e8-849f-e9f2a905f663.jpg)

**Comment by eatskolnikov** [comment]
@ivanatista We are waiting for the PR mate

**Comment by codercampos** [comment]
I think We can close this one @eatskolnikov
