### ISSUE TITLE
Crear mantenimiento de compañías

### ISSUE THREAD

**Issue by EddyCordero** [Emplea-do/emplea_do#159]
Cuando voy a "Mi perfil"
![Screen Shot 2020-06-08 at 10 56 50 PM](https://user-images.githubusercontent.com/1693000/84101262-89059d80-a9db-11ea-90d3-673b30934877.png)

Y doy click en la pestaña de perfiles de empresas
![Screen Shot 2020-06-08 at 10 56 46 PM](https://user-images.githubusercontent.com/1693000/84101259-886d0700-a9db-11ea-9a65-c69b959c6566.png)

Debe verse el listado de mis empresas y luego debo poder editar sus propiedades en la misma ventana.
Las empresas tienen un UserId y en el controller hay un _currentUser.UserId. Usando el CompanyService pueden cargar todas las empresas del usuario y listarlas.

_Originally posted by @eatskolnikov in https://github.com/Emplea-do/emplea_do/issues/123#issuecomment-640999334_

**Comment by eatskolnikov** [comment]
@EddyCordero  Trabaja con @juniorfelixgb en esto

**Comment by eatskolnikov** [comment]
@EddyCordero @juniorfelixgb 
Manden el PR con lo que tengas hasta ahora plz.
