### ISSUE TITLE
Unable to log in using Facebook or Linkedin

### ISSUE THREAD

**Issue by Jighdan** [Emplea-do/emplea_do#162]
## Describe the bug

Unable to log in using Facebook or Linkedin

## To Reproduce

1. Go to (https://emplea.do/Account/Login)[https://emplea.do/Account/Login]
2. Click on "Accede con Facebook" / "Accede con Linkedin"
3. Try to sig

## Screenshots

The error produced by an attempt to log in with Facebook
![image](https://user-images.githubusercontent.com/55284053/84969538-e9d15c00-b0e6-11ea-94f4-dae9ee073730.png)

**Comment by eatskolnikov** [comment]
We are remaking  the site, the old (current prod) site is currently being mostly unsupported until further notice.

**Comment by Jighdan** [comment]
:+1:
