### ISSUE TITLE
Dockerize the web application

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#165]
To avoid compatibility issues with the SQLite database vs the production SQL Server database

- Create a docker file for an SQL server instance and a docker.sh script
- Make the migrations run on the dockerized sql server database
- Change migrations to run on the sql server database
- Add script to init.sh for docker initialization
- Add readme for docker installation

**Comment by mecm1993** [comment]
Hi @eatskolnikov , I would like to work on this issue

**Comment by eatskolnikov** [comment]
Go for it @mecm1993
