### ISSUE TITLE
Agregar manejo de banners

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#166]
Como usuario quiero tener una pestaña para definir banners dentro de mi manejo de perfil.

- No puedo mandar banners hasta tener el flag activado para manejar banners
- Alguien debe aceptar los banners por slack
- Los banners van a manejar subida de archivos
- Como usuario quiero poder previsualizar un banner

### Entidad

Banner : BaseEntity
- UserId
- ImageUrl
- DestinationUrl
- IsApproved

## Acciones
- [x] Agregar entidad de banner
- [x] Agregar pestaña y formulario para manejo de banners
- [x] Agregar flag de IsEnabledForBanners a la entidad de usuario
- [x] Agregar flujo de slack para aprobar banners

**Comment by EddyCordero** [comment]
I'm here

**Comment by robertlluberes** [comment]
Cerraré este Issue dado que fue trabajado en el PR #226 

Sin embargo, algunos comentarios del PR no fueron resueltos, por lo que abriré un nuevo Issue con los mismos:

- Renombrar el endpoint _Wizard_ a _Create_ en _CompaniesController_ https://github.com/Emplea-do/emplea_do/pull/226#discussion_r506954188
- Renombrar la vista _Wizard_ a _Create_ en _Web/Views/Banners/_ https://github.com/Emplea-do/emplea_do/pull/226#discussion_r506954421
