### ISSUE TITLE
Migrate the old data

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#18]
We need to create a script to migrate the currently available data and moves it to the new model

**Comment by Cesarlachapelle** [comment]
How we are going to accomplish this ? we will load the data in one go or we will load small batches.

**Comment by eatskolnikov** [comment]
@Cesarlachapelle it's not a huge load, we just need to take the time to create a few queries and transform the old entities to the new model.

**Comment by robertlluberes** [comment]
Hola @eatskolnikov, me parece que esto se completó, si es así, favor cerrar este Issue.
