### ISSUE TITLE
Agregar texto de "Visita el sitio web de xxxx"

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#182]
En el detalle de empleo, en el area de empresa incluir el texto "Visita el sitio web de " para que quede claro que pueden acceder al link
![Screen Shot 2020-07-20 at 10 09 17 PM](https://user-images.githubusercontent.com/1693000/88004805-d21a3880-cad5-11ea-8602-5c97557946e4.png)

**Comment by josejavierpaez** [comment]
I will work  it tomorrow

**Comment by jpozo20** [comment]
Adicional, agregar los enlaces adecuados a cada imagen. Actualmente sólo te llevan al hash (#).

**Comment by JhonasV** [comment]
Me gustaría tomar este issue si nadie lo ha trabajado @eatskolnikov

**Comment by robertlluberes** [comment]
> 
> 
> Me gustaría tomar este issue si nadie lo ha trabajado @eatskolnikov

Asignado. @JhonasV

**Comment by Jadhielv** [comment]
Done @robertlluberes. Check **_PR_**: #228
