### ISSUE TITLE
Remover código legacy y comentarios

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#185]
En el controller de jobs hay código explicitamente creado para mantener la versión legacy. Vamos a removerlo para que el código sea más legible.

**Comment by robertlluberes** [comment]
@eatskolnikov Quisiera trabajar este Issue, pero me gustaria saber si el alcance seria solo para JobsController, ya que hay otras cosas que se pueden mejorar, ver ejemplos más abajo:

Comentarios en **JobsServices**
https://github.com/Emplea-do/emplea_do/blob/62abffb85b32e742e9e34de2b8e6bb2479def0dd/AppServices/Services/JobsService.cs#L129-L240

## Simplificar sentencias

Ejemplo: `String` -> `string`
https://github.com/Emplea-do/emplea_do/blob/62abffb85b32e742e9e34de2b8e6bb2479def0dd/Web/Controllers/JobsController.cs#L287

Ejemplo: `Int32` -> `int`
https://github.com/Emplea-do/emplea_do/blob/62abffb85b32e742e9e34de2b8e6bb2479def0dd/Web/Controllers/JobsController.cs#L290

## Eliminar comentarios obvios:
https://github.com/Emplea-do/emplea_do/blob/62abffb85b32e742e9e34de2b8e6bb2479def0dd/Web/Controllers/JobsController.cs#L328

https://github.com/Emplea-do/emplea_do/blob/62abffb85b32e742e9e34de2b8e6bb2479def0dd/Web/Controllers/JobsController.cs#L332

Eliminar using innecesarios, etc

**Comment by eatskolnikov** [comment]
@robertlluberes Vamos a limitarnos a los comentarios, usar String o string no es realmente un issue y puede traer conflictos con otros PR's que se están trabajando.
