### ISSUE TITLE
Colocar llamado a acción para compartir trabajos en redes sociales

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#187]
Encima de la sección donde está la información de la empresa en el detalle de una posición. 
Incluye 2 botones para compartir en Facebook y Twitter

**Comment by JhonasV** [comment]
I would like to take this issue. @eatskolnikov

**Comment by robertlluberes** [comment]
Ceraré ste Issue, el llamado a la acción de compartir el empleo en _Twitter_ y _Facebook_ está presente y funcionando.

![image](https://user-images.githubusercontent.com/13991439/95397877-58bf0480-08d2-11eb-91a8-27ec1d645fa1.png)
