### ISSUE TITLE
Barra de Mantenimiento Visible

### ISSUE THREAD

**Issue by ljcordero** [Emplea-do/emplea_do#190]
## Describe the bug

Actualmente se muestra la barra de mantenimiento en el detalle de un trabajo para usuarios no autorizados ni autenticados.

## To Reproduce

Ejemplo: https://beta.emplea.do/Jobs/Details/1067

![mantenimiento-bar-visible](https://user-images.githubusercontent.com/29816580/88324914-62cd6000-ccf2-11ea-80da-12783c6ed425.gif)

Aunque el editar te envía a la página de login, el ocultar y el borrar no lo hacen e intentan realizar la acción.

![image](https://user-images.githubusercontent.com/29816580/88325035-88f30000-ccf2-11ea-86b9-817a336e51fe.png)

**Comment by eatskolnikov** [comment]
El edit hace un redirect y las otras operaciones se realizan por ajax. La solución de este problema es mostrar un mensaje de error al usuario cuando intente darle a esas opciones y falle la operación. En js al método $.post se le puede concatenar una llamada a .fail(callback) para entonces mostrar este mensaje de error.

Creo que es algo como esto:

```js
$.post().fail(function(error){ alert(error); } )
```

**Comment by ljcordero** [comment]
This is already fixed with commit: ca9c8bd1
However @eatskolnikov we should add another issue to handle all HTTP error (for user-friendly message) as you suggested here.
