### ISSUE TITLE
Mejora Contador de Visitas

### ISSUE THREAD

**Issue by ljcordero** [Emplea-do/emplea_do#191]
## Is your feature request related to a problem? Please describe.

Actualmente el contador de visitas de un trabajo aumenta en relación a la cantidad de veces que un trabajo en cliqueado.

![visitas-count](https://user-images.githubusercontent.com/29816580/88326238-d58b0b00-ccf3-11ea-8e57-ab6aca30fc7e.gif)

## Describe the solution you'd like

Implementar una validación que impida al mismo usuario aumentar en mas de 1 el contador de visitas.

**Comment by eatskolnikov** [comment]
Dale @ljcordero crea una cookie y guarda en ella los trabajos que ya he visitado como usuario. Del lado del servidor pregunta si el id del trabajo actual está en la cookie antes de mandar a incrementar el numero de las visitas
