### ISSUE TITLE
Link "Compañías que confían en nosotros" roto

### ISSUE THREAD

**Issue by ljcordero** [Emplea-do/emplea_do#192]
## Describe the bug

El link "Compañías que confían en nosotros" envía a la dirección: https://beta.emplea.do/companies la cual redirecciona al login.

## To Reproduce

![link](https://user-images.githubusercontent.com/29816580/88328535-94e0c100-ccf6-11ea-8d52-f1ed78e807d5.gif)

**Comment by erickconcepcion** [comment]
Entiendo que deberia ser anonimo, hay alguien trabajando esto?

**Comment by codercampos** [comment]
Closing this issue. Seems to be fixed.
