### ISSUE TITLE
Aplicar estilos en posiciones

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#193]
Un ejemplo https://beta.emplea.do/Jobs/Details/1065

<img width="806" alt="Screen Shot 2020-07-23 at 3 54 05 PM" src="https://user-images.githubusercontent.com/1693000/88332592-cd839900-ccfc-11ea-9187-22b4dd89753c.png">

**Comment by erickconcepcion** [comment]
Que estilo quieres que se aplique? puedes ser un poco mas especifico?

**Comment by eatskolnikov** [comment]
@erickconcepcion El texto se ve como todo pegado, los saltos de linea están como \n y deberían convertirse en <br/>

**Comment by jpozo20** [comment]
Para los que vean este issue, es tan simple como como este pequeño css:  `white-space: pre-line`.

Por cierto, @eatskolnikov creo que sería bueno agregarle clases a las diferentes partes del job si surgen más problemas de estilo en el futuro.
