### ISSUE TITLE
As a user I want to have a crud for jobs

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#2]
Just like in the old version

**Comment by codercampos** [comment]
I think this is done in my last PR, We can check it out later if you want

**Comment by christianrd** [comment]
Hi, how we going with it?

**Comment by codercampos** [comment]
@christianrd I have to re-check this later. I'm planning to start again on April

**Comment by christianrd** [comment]
@codercampos ok, let me know if you need a hands with it.

**Comment by eatskolnikov** [comment]
I'll be taking this now :p

**Comment by robertlluberes** [comment]
Closing this Issue, was done on PR #115
