### ISSUE TITLE
Issues con el form de crear nuevo job

### ISSUE THREAD

**Issue by jpozo20** [Emplea-do/emplea_do#205]
## Describe the bug

Actualmente hay algunos issues con el formulario de creación de nuevo job:

1. Los inputs están haciendo submit del form al presionar enter
2. El campo Sitio web dice que es opcional, pero la tabla tiene un NOT NULL constraint y da error al guardar
3. Los campos de HowToApply y Description pierden el formato al hacer submit del formulario y ocurre un error

## To Reproduce

Para el bug 1:
  - Ir al formulario de creación, llenar nombre y correo electrónico si es nuevo. 
  - Una vez llenos esos dos campos, los campos de texto y el de Localidad hacen submit al presionar enter

Para el bug 2:
  - Ir al formulario de creación, llenar todos los campos excepto sitio web. 
  - Al guardar aunque el campo dice que es opcional, genera un error debido al NOT NULL constraint en la tabla

Para el bug 2:
  - Ir al formulario de creación, llenar todos los campos excepto sitio web o título. 
  - Al guardar esos campos muestran que el campo es requerido, pero como se hace submit los editores de HowToApply y Description pierden los espacios y líneas.

## Expected behavior

- Los inputs no deben hacer submit al presionar enter. Ideal deshabilitar el submit y sólo manejarlo al dar click al botón.
- Si el campo de sitio web es opcional, no debería producir un error al estar vacío
- Si un campo genera un error, los editores de texto no debe perder el formato 

## Specifications

- **Operating System:** macOS Catalina v10.15.4
- **Browser:** Google Chrome v84.0.4147.68, Opera v66.0.3515.72
- **Emplea.do Version:** v1.0.0.0 ( aún no es posible saber la versión, see #103 )

## Other information

Para el tercer punto, creo que lo mejor es utilizar ajax en vez de hacer submit del form. 
O guardar el texto de los editores en el ViewState.

**Comment by GianCastle** [comment]
Por temas de accesibilidad de la web, el comportamiento esperado de los formularios es que al presionar enter estos hagan submit. Así lo especifica el standar de HTML

![image](https://user-images.githubusercontent.com/6842883/88875444-44360000-d1ef-11ea-91e9-9692432ae866.png)

Puedes ver más detalles sobre la especificación aquí. 👇🏽
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

**Comment by jpozo20** [comment]
Es la primera vez que leo sobre que ese es el comportamiento por default. 

De todas formas, el usuario nunca es de confiar que haga las cosas bien. Otro forma de abordarlo que leí, es presentar un confirm dialog al usuario para validar que no fue por error que le dió a la tecla.

**Comment by edwinfelipe** [comment]
Lo siento talvez entendi mal pero creo que dice que cuando el formulario tiene mas de un campo se deberia evitar hacer submit de manera implicita enl el penultimo parrafo
