### ISSUE TITLE
Link imágenes en lista inicial de jobs genera un 404

### ISSUE THREAD

**Issue by jpozo20** [Emplea-do/emplea_do#206]
## Describe the bug

Al hacer click al enlace de la imagen de cada job en la lista del home page, lanza un 404 al no encontrar el archivo.

## To Reproduce

- Ir al home page
- Dar click al link en cualquiera de las imágenes de los jobs

## Expected behavior

Si la imagen debe tener un link, esta debe llevarme a la imagen original

## Screenshots

![issue-jobs-image](https://user-images.githubusercontent.com/9166182/88486797-4af21800-cf4e-11ea-8b23-ea1f08c21bc4.png)

## Specifications

- **Operating System:** macOS Catalina v10.15.4
- **Browser:** Google Chrome v84.0.4147.68, Opera v66.0.3515.72
- **Emplea.do Version:** v1.0.0.0 ( aún no es posible saber la versión, see #103 )

## Other information

¿@eatskolnikov es necesario que las imágenes tengan ese enlace? El bug se puede arreglar con sólo quitar el link.

**Comment by JhonasV** [comment]
Me gustaría tomar este issue si nadie lo ha trabajado @eatskolnikov

**Comment by eatskolnikov** [comment]
El problema aquí es que el link debería mandar a la url de /Company/{id} para ver los trabajos de esa compañía. El link se está formando mal, esto se puede resolver con una @ donde se construye la URL

**Comment by JhonasV** [comment]
Este issue depende del merge del PR #217 @eatskolnikov

**Comment by JhonasV** [comment]
@eatskolnikov ya pueden cerrar este issue, se resolvió con el PR #217 y este se encuentra en PROD.

**Comment by robertlluberes** [comment]
> 
> 
> @eatskolnikov ya pueden cerrar este issue, se resolvió con el PR #217 y este se encuentra en PROD.

Confirmado, gracias
