### ISSUE TITLE
Visual improvements to the vacancies post cards for web and mobile 

### ISSUE THREAD

**Issue by jlebreault** [Emplea-do/emplea_do#207]
Little changes to improve the visual hierarchy and information architecture for the cards

Here is the example: https://xd.adobe.com/view/b964bb46-5e8b-4d61-976c-ef1255771e6d-ec37/

**Comment by codercampos** [comment]
I can get this.

**Comment by codercampos** [comment]
PR #219 has implemented this improvement.
