### ISSUE TITLE
Include opencollective donors in credits

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#21]
Include opencollective donors in credits

Endpoint for reference
https://opencollective.com/empleo-dot-net/members/all.json

**Comment by robertlluberes** [comment]
@eatskolnikov 

This is the actual Endpoint reference for opencollective donors

https://opencollective.com/emplea_do/members/all.json

I could work on this issue

**Comment by robertlluberes** [comment]
There is nothing to do with this issue, it's already implemented in **/sponsors**

Visual Aids:
