### ISSUE TITLE
el script para inicializar el proyecto en windows (init.bat) esta roto

### ISSUE THREAD

**Issue by varlackc** [Emplea-do/emplea_do#223]
## El Script para inicializar el proyecton en windows (init.bat) esta roto

Cuando el projecto es creado por primera vez en windows, y el init.bat script se utiliza para poblar la base de datos usando fluent migrator, el script muestra varios errores. Adicionalmente, los comentarios en el script init.bat muestran un error cuando el script init.bat es ejecutado 

## Reproducir el error

Pasos para reproducir el error

1. Abrir el projecto en una maquina de windows sin fluent migrator
2. Abrir la terminal CMD en modo de administrador
3. Navegar hasta el folder donde se encuentra el script init.bat en CMD
4. Ejecutar el script en la terminal CMD init.bat

## Expected behavior

La applicacion mostrara errores donde los comentarios estaban supuestos a 
aparecer

## Especificaciones

- **Systema Operativo:** [Windows 10]
- **Browser:** [e.g. chrome v83.0.4103.97]
- **Emplea.do Version:** [e.g. v1.0.0.0]

**Comment by robertlluberes** [comment]
Esoy cerrando este Issue, ya que fue resuelto en el PR [Reparar los errores en el script init.bat #224](https://github.com/Emplea-do/emplea_do/pull/224)
