### ISSUE TITLE
Las publicaciones salen con tipo "Web designer" por defecto aunque el usuario lo especifica en el job post

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#229]
Las publicaciones salen con tipo "Web designer" por defecto aunque el usuario lo especifica en el job post
![WhatsApp Image 2020-11-18 at 9 55 34 AM](https://user-images.githubusercontent.com/1693000/99546203-92ccfd00-298c-11eb-8a1f-0418aee200e9.jpeg)

**Comment by EddyCordero** [comment]
I'm here
