### ISSUE TITLE
Error producido cuando se trata de registrar compañía y el sitio web se deja empty 

### ISSUE THREAD

**Issue by javierbeltran** [Emplea-do/emplea_do#232]
Traté de registrar una compañía y dejé el campo sitio web vacío.

![image](https://user-images.githubusercontent.com/40900147/101291004-133c8c00-37dc-11eb-848e-138b2673193a.png)

**Comment by Orbis25** [comment]
i'm here!

**Comment by ZabalaMelendez** [comment]
Me gustaria aportar en este bug, por favor asignarmelo. Gracias!

**Comment by ZabalaMelendez** [comment]
??

**Comment by robertlluberes** [comment]
This is solved on PR #245
