### ISSUE TITLE
Agregar servicio de slack

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#46]
Debo poder enviar una solicitud de aprobación a slack

**Comment by cvivieca** [comment]
Solo para aclarar @eatskolnikov, el comportamiento que se desea es el siguiente:

1. Un usuario publica una nueva oferta de empleo. 
2. Se envía el titulo, descripción y usuario por Slack solicitando una aprobación.
3. Si se aprueba se elimina, en caso de no aprobarse ¿se le da un **feedback** al usuario de que cambiar o se pierde dicha oferta?

**Comment by eatskolnikov** [comment]
Sí, el feedback del usuario es que hay un flag de "Rejected" en la posición, cuando el entre va a ver que dice "Esta posición ha sido rechazada."

Para muestra de como se ve en slack mira estas imágenes:

![Screen Shot 2019-08-29 at 5 31 22 PM](https://user-images.githubusercontent.com/1693000/63977842-d6cf9b80-ca82-11e9-8c78-cdfbc427ec9d.png)

![Screen Shot 2019-08-29 at 5 30 53 PM](https://user-images.githubusercontent.com/1693000/63977824-c7e8e900-ca82-11e9-9e19-ee4850596270.png)

**Comment by eatskolnikov** [comment]
@cvivieca ¿Quieres que te lo asigne?

**Comment by cvivieca** [comment]
Si, por favor.

**Comment by cvivieca** [comment]
Hey @eatskolnikov esta semana subo el PR. Lo tuve que pausar unos días por temas de trabajo. 😎

**Comment by eatskolnikov** [comment]
@cvivieca ok

**Comment by robertlluberes** [comment]
If I'm not wrong, you already work on this feature @eatskolnikov , according to [this tweet](https://twitter.com/eatskolnikov/status/1269753105865945088). So, this Issue can be closed
