### ISSUE TITLE
Error en inicio de sesión con Google

### ISSUE THREAD

**Issue by granalberto** [Emplea-do/emplea_do#48]
Desde aquí: https://emplea.do/account/login

Elijo la opción **ACCEDE CON GOOGLE** y me lleva al inicio de sesión en Google. Como tengo varias cuentas activas, me permite seleccionar con cuál quiero iniciar sesión. Elijo la cuenta deseada y me devuelve al mismo sitio de emplea.do para iniciar sesión, como si no hubiese hecho nada previamente.

**Comment by eatskolnikov** [comment]
@granalberto mandame un correo a enmanuel@megsoftconsulting.com o escribe a la página de facebook con los detalles de la posición

**Comment by christianrd** [comment]
@eatskolnikov no se debería cerrar este Issue?

**Comment by robertlluberes** [comment]
> Error en inicio de sesión con Google

Este _bug_ es especifico para el inicio de sesión con _Google_, el día de hoy no he podido reproducirlo. 

He iniciado sesión correctamente eligiendo mi cuenta entre un listado de cuentas de Google disponibles en mi navegador, _por lo que estaré cerrando este bug_.

![image](https://user-images.githubusercontent.com/13991439/201201843-ce5fef23-9454-40b1-834f-73086392d2d6.png)

Adicionalmente el issue relacionado, ha sido cerrado.

[#49 - Configurar autenticación](https://github.com/Emplea-do/emplea_do/issues/49)
