### ISSUE TITLE
Auto publicar posiciones en twitter

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#50]
Cuando se apruebe un job se debe publicar en twitter automaticamente. 

Para referencia:
https://twitter.com/emplea_do

**Comment by Cesarlachapelle** [comment]
asigname este issue

**Comment by eatskolnikov** [comment]
@Cesarlachapelle ¿cómo va este issue?

**Comment by Cesarlachapelle** [comment]
ohh sorry, its ready, hice el pull request ya

**Comment by christianrd** [comment]
creo que este issue ya se puede cerrar -> #98
