### ISSUE TITLE
Crear pantalla de mantenimiento de perfil de usuario

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#52]
Para referencia
http://codeminifier.com/workio-job-board-template/workio/employer-dashboard.html

- [ ] Crea los partial views de las secciones de la página
- [ ] Agrega el ViewModel

**Comment by eatskolnikov** [comment]
@HommyDeJ This one

**Comment by HommyDeJ** [comment]
@eatskolnikov  .

**Comment by icepeda** [comment]
Asigna este issue a mi por favor
