### ISSUE TITLE
Agregar proyecto de unit tests

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#61]

**Comment by Richard809** [comment]
Do you have a testing framework in mind? Are there any specific areas needing unit tests right now? How can I help?

**Comment by eatskolnikov** [comment]
Plain ol' Nunit for now, we will focus on this effort after we publish the new site. For now you can help with trying to make sense of PR #68

**Comment by Richard809** [comment]
That PR is already merged 👀

**Comment by eatskolnikov** [comment]
@Richard809 I merged it, dale con nunit

**Comment by Richard809** [comment]
@eatskolnikov will do
