### ISSUE TITLE
Documentar proceso de obtención de los keys y client ids para autenticación

### ISSUE THREAD

**Issue by eatskolnikov** [Emplea-do/emplea_do#71]
Agrega un archivo aparte llamado Authentication.md
Referencia el archivo en el readme.md

- [ ] Documentación de Facebook
- [ ] Documentación de Microsoft
- [ ] Documentación de Linkedin
- [ ] Documentación de Github
- [ ] Documentación de Google

Por favor comentar el issue #49 cuando se termine

**Comment by eatskolnikov** [comment]
@robertlluberes te lo voy a asignar, comenta plz thnx 🙆🏽‍♂️

**Comment by robertlluberes** [comment]
Dale, asignarlo @eatskolnikov 

Podrias darme más detalles, lo quieres con imágenes, ejemplo real, etc?

**Comment by eatskolnikov** [comment]
@robertlluberes sí incluye imágenes y prepara las guías step by step en un lenguaje llano e incluye urls. 

Algo como:

0. Go to xyz.com and click the "lorem ipsum button" at the top of the screen
[ Here goes an image with the lorem ipsum button higlighted ]
1. ...
2. ...
3. ...
n-1. Copy the *Client Id* and paste it in the *ClientId* string for xyz within the application.Development.json file 
n. Copy the *Client Secret* and paste it in the *ClientId* string for xyz within the application.Development.json file
